[workspace]
members = [
    "crates/openhp1-audio",
    "crates/openhp1-game",
    "crates/openhp1-map",
    "crates/openhp1-mesh",
    "crates/openhp1-package",
    "crates/openhp1-physics",
    "crates/openhp1-render",
    "crates/openhp1-runtime",
    "crates/openhp1-scene",
    "crates/openhp1-script",
    "crates/openhp1-texture",
    "crates/openhp1-viewer",
]
resolver = "3"

[workspace.package]
edition = "2024"
license = "MIT OR Apache-2.0"
rust-version = "1.97"

[workspace.dependencies]
anyhow = "1.0"
bytemuck = { version = "1.24", features = ["derive"] }
eframe = { version = "0.35", default-features = false, features = ["default_fonts", "wgpu", "wayland", "x11"] }
egui = "0.35"
egui-wgpu = { version = "0.35", default-features = false }
egui-winit = { version = "0.35", default-features = false, features = ["wayland", "x11"] }
glam = "0.30"
pollster = "0.4"
kira = { version = "0.12", default-features = false, features = ["cpal", "mp2", "pcm", "wav"] }
mint = "0.5"
rustc-hash = "2.1"
thiserror = "2.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
wgpu = "29"
winit = { version = "0.30", default-features = false, features = ["rwh_06", "wayland", "x11"] }

[profile.dev]
debug = 1
codegen-units = 512
opt-level = 0
lto = "off"

[profile.dev.package."*"]
codegen-units = 128