#[derive(Copy, Clone, Debug, Eq, PartialEq)]
pub(crate) enum Opcode {
    LocalVariable,
    InstanceVariable,
    DefaultVariable,
    Return,
    Switch,
    Jump,
    JumpIfNot,
    Stop,
    Case,
    Nothing,
    LabelTable,
    GotoLabel,
    EatString,
    Let,
    LetBool,
    DynArrayElement,
    DynArrayToInt,
    Unknown0x15,
    EndFunctionParms,
    SelfObject,
    Skip,
    ClassContext,
    MetaCast,
    Context,
    ArrayElement,
    VirtualFunction,
    FinalFunction,
    IntConst,
    FloatConst,
    StringConst,
    ObjectConst,
    NameConst,
    RotationConst,
    VectorConst,
    ByteConst,
    IntZero,
    IntOne,
    True,
    False,
    NoObject,
    Unknown0x2b,
    IntConstByte,
    BoolVariable,
    DynamicCast,
    Iterator,
    IteratorPop,
    IteratorNext,
    StructMember,
    GlobalFunction,
    Conversion(ConversionOpcode),
    ExtendedNative(u16),
    Native(u16),
    Unsupported,
}

impl From<u8> for Opcode {
    fn from(opcode: u8) -> Self {
        match opcode {
            0x00 => Self::LocalVariable,
            0x01 => Self::InstanceVariable,
            0x02 => Self::DefaultVariable,
            0x04 => Self::Return,
            0x05 => Self::Switch,
            0x06 => Self::Jump,
            0x07 => Self::JumpIfNot,
            0x08 => Self::Stop,
            0x0a => Self::Case,
            0x0b => Self::Nothing,
            0x0c => Self::LabelTable,
            0x0d => Self::GotoLabel,
            0x0e => Self::EatString,
            0x0f => Self::Let,
            0x10 => Self::DynArrayElement,
            0x14 => Self::LetBool,
            0x15 => Self::Unknown0x15,
            0x16 => Self::EndFunctionParms,
            0x17 => Self::SelfObject,
            0x18 => Self::Skip,
            0x12 => Self::ClassContext,
            0x13 => Self::MetaCast,
            0x19 => Self::Context,
            0x1a => Self::ArrayElement,
            0x1b => Self::VirtualFunction,
            0x1c => Self::FinalFunction,
            0x1d => Self::IntConst,
            0x1e => Self::FloatConst,
            0x1f => Self::StringConst,
            0x20 => Self::ObjectConst,
            0x21 => Self::NameConst,
            0x22 => Self::RotationConst,
            0x23 => Self::VectorConst,
            0x24 => Self::ByteConst,
            0x25 => Self::IntZero,
            0x26 => Self::IntOne,
            0x27 => Self::True,
            0x28 => Self::False,
            0x2a => Self::NoObject,
            0x2b => Self::Unknown0x2b,
            0x2c => Self::IntConstByte,
            0x2d => Self::BoolVariable,
            0x2e => Self::DynamicCast,
            0x2f => Self::Iterator,
            0x30 => Self::IteratorPop,
            0x31 => Self::IteratorNext,
            0x36 => Self::StructMember,
            0x37 => Self::DynArrayToInt,
            0x38 => Self::GlobalFunction,
            0x39..=0x60 => Self::Conversion(opcode.into()),
            0x61..=0x6f => Self::ExtendedNative(u16::from(opcode - 0x60) << 8),
            0x70..=0xff => Self::Native(u16::from(opcode)),
            _ => Self::Unsupported,
        }
    }
}

#[derive(Copy, Clone, Debug, Eq, PartialEq)]
pub(crate) enum ConversionOpcode {
    RotatorToVector,
    ByteToInt,
    ByteToBool,
    ByteToFloat,
    IntToByte,
    IntToBool,
    IntToFloat,
    BoolToByte,
    BoolToInt,
    BoolToFloat,
    FloatToByte,
    FloatToInt,
    FloatToBool,
    ObjectToBool,
    NameToBool,
    StringToByte,
    StringToInt,
    StringToBool,
    StringToFloat,
    StringToVector,
    StringToRotator,
    VectorToBool,
    VectorToRotator,
    RotatorToBool,
    ByteToString,
    IntToString,
    BoolToString,
    FloatToString,
    ObjectToString,
    NameToString,
    VectorToString,
    RotatorToString,
    StringToName,
    Unsupported,
}

impl From<u8> for ConversionOpcode {
    fn from(opcode: u8) -> Self {
        match opcode {
            0x39 => Self::RotatorToVector,
            0x3a => Self::ByteToInt,
            0x3b => Self::ByteToBool,
            0x3c => Self::ByteToFloat,
            0x3d => Self::IntToByte,
            0x3e => Self::IntToBool,
            0x3f => Self::IntToFloat,
            0x40 => Self::BoolToByte,
            0x41 => Self::BoolToInt,
            0x42 => Self::BoolToFloat,
            0x43 => Self::FloatToByte,
            0x44 => Self::FloatToInt,
            0x45 => Self::FloatToBool,
            0x47 => Self::ObjectToBool,
            0x48 => Self::NameToBool,
            0x49 => Self::StringToByte,
            0x4a => Self::StringToInt,
            0x4b => Self::StringToBool,
            0x4c => Self::StringToFloat,
            0x4d => Self::StringToVector,
            0x4e => Self::StringToRotator,
            0x4f => Self::VectorToBool,
            0x50 => Self::VectorToRotator,
            0x51 => Self::RotatorToBool,
            0x52 => Self::ByteToString,
            0x53 => Self::IntToString,
            0x54 => Self::BoolToString,
            0x55 => Self::FloatToString,
            0x56 => Self::ObjectToString,
            0x57 => Self::NameToString,
            0x58 => Self::VectorToString,
            0x59 => Self::RotatorToString,
            0x5a => Self::StringToName,
            _ => Self::Unsupported,
        }
    }
}
