[package]
name = "openhp1-scene"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
glam.workspace = true
openhp1-map = { path = "../openhp1-map" }
openhp1-mesh = { path = "../openhp1-mesh" }
openhp1-package = { path = "../openhp1-package" }
openhp1-script = { path = "../openhp1-script" }
openhp1-texture = { path = "../openhp1-texture" }
tracing.workspace = true

[dev-dependencies]
openhp1-runtime = { path = "../openhp1-runtime" }
